---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-kernelspecs
  namespace: enterprise-gateway
  labels:
    app: enterprise-gateway
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
